# For more information: https://laravel.com/docs/sail
version: '3'
services:
    traefik:
        image: "traefik:v2.9"
        command:
            - --entrypoints.web.address=:80
            - --providers.docker
            - --providers.docker.network=demo-network
            - --api.dashboard=true
            - --serversTransport.insecureSkipVerify=true
            - --providers.docker.exposedByDefault=false
            - --api.insecure
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        labels:
            - "traefik.enable=true"
        restart: always
        networks:
            - demo-network

    payment:
        build:
            context: ./payment
            dockerfile: Dockerfile
            args:
                UID: '${DOCKER_UID:-1000}'
                GID: '${DOCKER_GID:-1000}'
        image: tecnosys-ecommerce-demo/payment
        volumes:
            - './payment:/var/www/html'
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.payment.rule=Host(`payment.ecommerce.test`)"
            - "traefik.http.routers.payment.entrypoints=web"
            - "traefik.http.services.payment.loadbalancer.server.port=80"
            - "traefik.http.services.payment.loadbalancer.server.scheme=http"
        networks:
            - demo-network
        depends_on:
            - mariadb
            - mailhog

    wordpress:
        build:
            context: ./wordpress
            dockerfile: Dockerfile
            args:
                UID: '${DOCKER_UID:-1000}'
                GID: '${DOCKER_GID:-1000}'
        image: tecnosys-ecommerce-demo/wordpress
        volumes:
            - './wordpress:/var/www/html'
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.wordpress.rule=Host(`ecommerce.test`)"
            - "traefik.http.routers.wordpress.entrypoints=web"
            - "traefik.http.services.wordpress.loadbalancer.server.port=80"
            - "traefik.http.services.wordpress.loadbalancer.server.scheme=http"
        networks:
            - demo-network
        depends_on:
            - mariadb
            - mailhog

    mariadb:
        image: 'mariadb:10'
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'payment'
            MYSQL_USER: 'MYSQL_USER'
            MYSQL_PASSWORD: 'root'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'demo-mariadb:/var/lib/mysql'
            - './etc/mariadb/create-wordpress-database.sh:/docker-entrypoint-initdb.d/10-create-wordpress-database.sh'
        networks:
            - demo-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-proot"]
            retries: 3
            timeout: 5s
            
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - demo-network

networks:
    demo-network:
        driver: bridge

volumes:
    demo-mariadb:
        driver: local