# For more information: https://laravel.com/docs/sail
version: '3'
services:
    payment:
        build:
            context: ./payment
            dockerfile: Dockerfile
            args:
                UID: '${DOCKER_UID:-1000}'
                GID: '${DOCKER_GID:-1000}'
        image: tecnosys-ecommerce-demo/payment
        ports:
            - 80:80
        volumes:
            - './payment:/var/www/html'
        networks:
            - demo-network
        depends_on:
            - mariadb
            - mailhog

    mariadb:
        image: 'mariadb:10'
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'payment'
            MYSQL_USER: 'MYSQL_USER'
            MYSQL_PASSWORD: 'root'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'demo-mariadb:/var/lib/mysql'
            - './etc/mariadb/create-wordpress-database.sh:/docker-entrypoint-initdb.d/10-create-wordpress-database.sh'
        networks:
            - demo-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-proot"]
            retries: 3
            timeout: 5s
            
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - demo-network

networks:
    demo-network:
        driver: bridge

volumes:
    demo-mariadb:
        driver: local